title: Seulki Han  # You can add your name here
logo: photo_profile.png # Use a relative path to logo image 
description: Ph. D. Candidate at University of Connecticut # Fix hyphenation 
show_downloads: false # Fix spelling
theme: jekyll-theme-minimal 
email: seulki.han@uconn.edu # Allow visitors to contact you
